### ISSUE TITLE
[Bug] Appointments not displayed on website

### ISSUE THREAD

**Issue by guilmant** [rotaract/rotaract-appointments#106]
Specifically reported by District 1860: Appointments from October on are not displayed on the website, although settings look correct in _mein Rotaract_.

**Comment by guilmant** [comment]
Yes. For example, in 1860 they have an event in October and one in November 2022 per _mein Rotaract_.
On their website the plugin only displays events starting from July 2023.

**Comment by zimbcode** [comment]
It was just the fact that you tried to embed too many calendars with too many appointments. The result limit of the Elasticsearch query was set to 100. xD
