### ISSUE TITLE
When subscribing to multiple calender the source calender is not displayed

### ISSUE THREAD

**Issue by trigion** [rotaract/rotaract-appointments#108]
When subscribing to multiple calender the source calender is not displayed. E.g. a district is subscribing to the calender of all the clubs in the district. The calender should be shown at the district page. It can not be seen which clubcalender is the source of a appointment.

**Comment by trigion** [comment]
Exactly. I dont have any JS Skills and also hadnt time yet - but i want to take a look into it. When you are working on it - Let me know, maybe i can be use- or helpful

**Comment by guilmant** [comment]
Man, you're on a great run today @zimbcode!

Maybe you could look into the alignment of the color dot and the appointment owner text, e.g. in standard width listQuarter view.
