### ISSUE TITLE
Das Plugin kann nicht aktiviert werden, da es einen fatalen Fehler erzeugt.

### ISSUE THREAD

**Issue by sunilgknair051** [rotaract/rotaract-appointments#130]
Hallo, wir sind der Rotaract Club Clausthal-Zellerfeld, mein Vorgänger hatte sich lange Zeit nicht für ein Hosting durch rotaract entschieden und ich als Webmaster bin diesem Beispiel gefolgt und wir hosten privat.  Ich versuche gerade ein paar Dinge in unsere WordPress Seite einzubauen und als ich versucht habe das Termin-Plugin einzubauen, bekomme ich diesen Fehler.

`Parse error: syntax error, unexpected 'Rotaract_Appointments_Loader' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/rotaract/public_html/wp/wp-content/plugins/rotaract-appointments/includes/class-rotaract-appointments.php on line 39
`

Kann mir das jemand erklären?

**Comment by bbenno** [comment]
Hi Sunil,

would you mind telling me: how did you install the plugin in your WordPress instance?
The plugin works only when you use the pre-build [ZIP file](https://github.com/rotaract/rotaract-appointments/releases/latest/download/rotaract-appointments.zip).

**Comment by sunilgknair051** [comment]
Hi Benno,
I just downloaded the zip from the repo and uploaded on our WordPress plugin site and installed it successfully. But, when I click on activate the plugin, I get this error.

**Comment by bbenno** [comment]
Which PHP are you using?

**Comment by sunilgknair051** [comment]
**7.2.34** 
Well, I did try to find the cause and used a PHP compatibility checker. This version could be an issue. :(

**Comment by bbenno** [comment]
lol, well... it seems this version is [EOL since end of 2020](https://www.php.net/supported-versions.php). Highly recommend upgrading to an active supported version (8.0 or higher).
We cannot (and will not, for obvious reasons) provide support for EOL PHP versions and will therefore close this issue.
Despite, I will contact you privately due to some challenges you will run into at some point.
