### ISSUE TITLE
Can not add multiple sources for events

### ISSUE THREAD

**Issue by ppiontek** [rotaract/rotaract-appointments#135]
When trying to add multiple sources for events (e. g. a club + MDIO) you can only choose one source. Trying to add a second source via the button does not work.

**Comment by guilmant** [comment]
This has been re-emphasized by some people in our Zoom event today :D

**Comment by zimbcode** [comment]
Does 82eeefb9356cb9122a3217ed9a2e9ddca7184eb5 fix that problem? Otherwise I don't understand this issue.

**Comment by guilmant** [comment]
Let me try a more detailed explanation:

In the WordPress interface of the plugin, cannot successfully add or remove a host (Veranstalter). The GUI shows "settings saved" when clicking the button "add" ("+Hinzufügen") or "x", but no field shows/disappears, thus nothing can be added.

This has been observed e.g. on d1810. and demo., but not on d1841. afaik.

**Comment by zimbcode** [comment]
This should be fixed by now

**Comment by guilmant** [comment]
Looks good on demo. Thanks!
